/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPaktManager } from "./IPaktManager";
export type { WithdrawContractTest } from "./WithdrawContractTest";
