/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as paktManagerSol from "./PaktManager.sol";
export type { paktManagerSol };
import type * as test from "./test";
export type { test };
export type { PaktToken } from "./PaktToken";
