/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPaktManager,
  IPaktManagerInterface,
} from "../../../../contracts/test/WithdrawContractTest.sol/IPaktManager";

const _abi = [
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPaktManager__factory {
  static readonly abi = _abi;
  static createInterface(): IPaktManagerInterface {
    return new utils.Interface(_abi) as IPaktManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPaktManager {
    return new Contract(address, _abi, signerOrProvider) as IPaktManager;
  }
}
