/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as withdrawContractTestSol from "./WithdrawContractTest.sol";
export type { withdrawContractTestSol };
